# Generated by Django 6.1 on 2026-08-18 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='herovideo',
            name='video_file',
        ),
        migrations.AddField(
            model_name='herovideo',
            name='video_url',
            field=models.URLField(default='https://example.com/video.mp4', verbose_name='رابط الفيديو (Vimeo/YouTube)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reelshowcase',
            name='row',
            field=models.PositiveSmallIntegerField(choices=[(1, 'الصف الأول'), (2, 'الصف الثاني'), (3, 'الصف الثالث')], default=1, verbose_name='الصف'),
        ),
        migrations.AddField(
            model_name='reelshowcase',
            name='views_label',
            field=models.CharField(blank=True, max_length=20, verbose_name='عدد المشاهدات (مثال: 7.4M)'),
        ),
        migrations.AlterField(
            model_name='herovideo',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
