# Generated by Django 6.1 on 2026-08-29 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_testimonial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herovideo',
            name='video_url',
            field=models.URLField(verbose_name='رابط الفيديو (يوتيوب)'),
        ),
    ]
