# Generated by Django 6.1.1 on 2026-09-07 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_alter_herovideo_video_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='name',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='text',
        ),
        migrations.AddField(
            model_name='testimonial',
            name='screenshot',
            field=models.ImageField(default='', upload_to='testimonials/', verbose_name='صورة الرأي (سكرين شوت)'),
            preserve_default=False,
        ),
    ]
